spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hierarchcal-data-db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create